// Regenerate Drizzle types from the Alembic-managed SQLite DB.
//
// Alembic owns the schema. `drizzle-kit pull` is used only to generate
// TypeScript table definitions; afterwards we:
//   1. delete the SQL migration + meta it emits (Drizzle must never migrate), and
//   2. strip CHECK constraints: drizzle-kit's SQLite introspection attaches every
//      table's CHECKs to every table and truncates them. They are DDL-only and
//      irrelevant to a read-only client (SQLite enforces the real ones).
//
// drizzle-kit 0.31 cannot parse multi-line CREATE VIEW statements ("Could not
// process view", exit 1), so we pull from a temporary copy of the DB with the
// views (v_*) dropped. The dashboard reads the views with raw SQL.
import { execSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

import Database from "better-sqlite3";
import { config } from "dotenv";

config({ path: ".env.local", quiet: true });
const source = resolve(process.env.DB_PATH ?? "../data/betpredictor.db");
const tmp = mkdtempSync(join(tmpdir(), "bp-pull-"));
const copy = join(tmp, "schema.db");
const sourceDb = new Database(source, { readonly: true, fileMustExist: true });
await sourceDb.backup(copy);
sourceDb.close();
const db = new Database(copy);
for (const { name } of db.prepare("SELECT name FROM sqlite_master WHERE type = 'view'").all()) {
  db.exec(`DROP VIEW "${name}"`);
}
db.close();

const out = "src/db/generated";
try {
  execSync("drizzle-kit pull", { stdio: "inherit", env: { ...process.env, DB_PATH: copy } });
} finally {
  rmSync(tmp, { recursive: true, force: true });
}

for (const f of readdirSync(out)) {
  if (f.endsWith(".sql") || f === "meta") rmSync(join(out, f), { recursive: true, force: true });
}

const schemaPath = join(out, "schema.ts");
let schemaSrc = readFileSync(schemaPath, "utf8");
schemaSrc = schemaSrc.replace(/^\s*check\(.*\),\r?\n/gm, "");
schemaSrc = schemaSrc.replace(/,\s*\(table\) => \[\s*\]\)/g, ")");
schemaSrc = schemaSrc.replace(/\bcheck, /, "");
const header =
  "// GENERATED by `pnpm db:pull` from the Alembic-managed database. Do not edit.\n" +
  "// Read-only: the dashboard never writes; all writes go through the FastAPI engine.\n";
writeFileSync(schemaPath, header + schemaSrc);
console.log("schema.ts regenerated (CHECK constraints stripped; Alembic enforces them).");
