// Regenerate Drizzle types from the Alembic-managed SQLite DB.
//
// Alembic owns the schema. `drizzle-kit pull` is used only to generate
// TypeScript table definitions; afterwards we:
//   1. delete the SQL migration + meta it emits (Drizzle must never migrate), and
//   2. strip CHECK constraints: drizzle-kit's SQLite introspection attaches every
//      table's CHECKs to every table and truncates them. They are DDL-only and
//      irrelevant to a read-only client (SQLite enforces the real ones).
import { execSync } from "node:child_process";
import { readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const out = "src/db/generated";
execSync("drizzle-kit pull", { stdio: "inherit" });

for (const f of readdirSync(out)) {
  if (f.endsWith(".sql") || f === "meta") rmSync(join(out, f), { recursive: true, force: true });
}

const schemaPath = join(out, "schema.ts");
let src = readFileSync(schemaPath, "utf8");
src = src.replace(/^\s*check\(.*\),\r?\n/gm, "");
src = src.replace(/,\s*\(table\) => \[\s*\]\)/g, ")");
src = src.replace(/\bcheck, /, "");
const header =
  "// GENERATED by `pnpm db:pull` from the Alembic-managed database. Do not edit.\n" +
  "// Read-only: the dashboard never writes; all writes go through the FastAPI engine.\n";
writeFileSync(schemaPath, header + src);
console.log("schema.ts regenerated (CHECK constraints stripped; Alembic enforces them).");
